<!-- Match Management Modal -->
<div class="modal fade" id="matchModal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content">
<div class="modal-header"><h5 class="modal-title" id="matchModalTitle">Series Control</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
<div class="modal-body"><input type="hidden" id="matchId"><div class="row g-3">
<div class="col-md-5"><label class="form-label">Team 1</label><div class="form-control" id="matchTeam1" style="background:var(--bg-primary)"></div></div><div class="col-md-2 text-center d-flex align-items-end justify-content-center pb-2"><strong>VS</strong></div><div class="col-md-5"><label class="form-label">Team 2</label><div class="form-control" id="matchTeam2" style="background:var(--bg-primary)"></div></div>
<div class="col-12" id="matchTeamEditor" style="display:none"><div class="card p-3 border-primary"><div class="d-flex justify-content-between align-items-center mb-2"><strong>Edit Bracket Teams</strong><small class="text-muted">Available before the match starts</small></div><div class="row g-2"><div class="col-md-5"><select id="matchTeam1Select" class="form-select"></select></div><div class="col-md-2 text-center d-flex align-items-center justify-content-center"><strong>VS</strong></div><div class="col-md-5"><select id="matchTeam2Select" class="form-select"></select></div><div class="col-12 text-end"><button type="button" class="btn btn-primary" onclick="saveMatchTeams()"><i class="bi bi-people"></i> Save Team Pairing</button></div></div></div></div>
<div class="col-md-4"><label class="form-label">Best Of</label><select id="matchBestOf" class="form-select"><option>BO1</option><option>BO2</option><option>BO3</option><option>BO5</option><option>BO7</option></select></div>
<div class="col-md-4"><label class="form-label">Status</label><select id="matchStatus" class="form-select"><option value="live">Live</option><option value="finished">Finished</option><option value="waiting">Not Started</option></select></div>
<div class="col-md-4"><label class="form-label">Current Score</label><div class="form-control text-center"><strong id="scoreDisplay">0 - 0</strong></div></div>
<div class="col-12"><div class="alert alert-info mb-0">Click the team that wins each game. TOURNIVOX automatically finishes the series when the required wins are reached. In Round Robin BO2, a 1-1 result is automatically recorded as a draw.</div></div>
<div class="col-md-6"><button type="button" id="team1GameWin" class="btn btn-primary w-100" onclick="recordGameWin(1)">Team 1 Won This Game</button></div>
<div class="col-md-6"><button type="button" id="team2GameWin" class="btn btn-danger w-100" onclick="recordGameWin(2)">Team 2 Won This Game</button></div>
<input type="hidden" id="matchTeam1Score" value="0"><input type="hidden" id="matchTeam2Score" value="0">
<div class="col-12"><label class="form-label">Notes</label><textarea id="matchNotes" class="form-control" rows="2"></textarea></div>
</div><div id="matchManageSection" style="display:none"><hr><div class="d-flex gap-2"><button type="button" class="btn btn-outline-primary" onclick="updateMatch()">Save Details</button><button type="button" class="btn btn-outline-warning" onclick="resetSeriesScore()">Reset Series Score</button></div></div></div>
<div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button></div></div></div></div>
